name: image_compressor
description: Compress & Format images (jpeg, png)
version: 1.0.0
repository: https://github.com/pikomit/image_compressor
homepage: https://github.com/pikomit/image_compressor#readme

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fr.supernovae.pikomit.image_compressor
        pluginClass: ImageCompressorPlugin
      ios:
        pluginClass: ImageCompressorPlugin
